// Renderers for the publishable report: Markdown and LaTeX are pure string
// builders with no dependencies; DOCX/PDF are produced by shelling out to
// `pandoc` from the generated Markdown, with a graceful, actionable error when
// pandoc is not installed.

import type {
  Manuscript,
  BibEntry,
  ManuscriptHypothesis,
} from "../models/manuscript.js";

const CITATION_FLAG: Record<string, string> = {
  fabricated: " ⚠️ unverified — no CrossRef match",
  unverified: " ⚠️ unverified",
  verified: "",
};

function markerList(nums: number[]): string {
  return nums.length ? ` [${nums.join(", ")}]` : "";
}

function formatReferenceText(e: BibEntry): string {
  const title = e.canonicalTitle ?? e.raw;
  const stripDot = (s: string) => s.replace(/\.\s*$/, "");
  const parts: string[] = [];
  if (e.authors) parts.push(stripDot(e.authors));
  if (e.year) parts.push(`(${e.year})`);
  parts.push(stripDot(title));
  const main = `${parts.join(". ")}.`;
  // Append a DOI link only when the title text doesn't already contain it
  // (raw citations that are themselves a doi.org URL would otherwise double up).
  const suffix = e.doi && !title.includes(e.doi) ? ` https://doi.org/${e.doi}` : "";
  return main + suffix;
}

// ─── Markdown ────────────────────────────────────────────────────────────────

export function toMarkdown(m: Manuscript): string {
  const L: string[] = [];
  L.push(`# ${m.title}`, "");
  L.push(`*Generated by co-scientist on ${m.generatedAt}*`, "");
  L.push(`> **Research goal.** ${m.researchGoal}`, "");

  L.push(`## Abstract`, "", m.abstract, "");
  L.push(`## 1. Background`, "", m.background, "");

  // Methods (deterministic)
  const me = m.methods;
  L.push(`## 2. Methods`, "");
  L.push(
    `Hypotheses were generated and ranked by the co-scientist multi-agent pipeline ` +
      `(${me.agents.join(", ")}) using the \`${me.model}\` language model` +
      `${me.seed != null ? `, seeded with \`${me.seed}\` for reproducibility` : ""}. ` +
      `The run produced ${me.totalHypotheses} hypotheses over ${me.rounds} round(s), ` +
      `adjudicated through ${me.totalMatches} pairwise Glicko-2 tournament matches` +
      `${me.budgetTokens ? `, under a ${me.budgetTokens.toLocaleString()}-token compute budget` : ""}.`,
    "",
  );

  // Results (deterministic)
  L.push(`## 3. Results`, "");
  L.push(`### 3.1 Ranked hypotheses`, "");
  L.push(`| Rank | Hypothesis | Rating (±RD) | W/L | Nov/Cor/Test |`);
  L.push(`|-----:|------------|-------------:|:---:|:------------:|`);
  for (const h of m.hypotheses) {
    const scores = [h.noveltyScore, h.correctnessScore, h.testabilityScore]
      .map((s) => (s == null ? "–" : String(s)))
      .join("/");
    L.push(
      `| ${h.rank} | ${h.title.replace(/\|/g, "\\|")} | ${Math.round(h.eloRating)} ±${Math.round(h.ratingDeviation)} | ${h.wins}/${h.losses} | ${scores} |`,
    );
  }
  L.push("");

  L.push(`### 3.2 Hypothesis details`, "");
  for (const h of m.hypotheses) {
    L.push(`#### ${h.rank}. ${h.title}${markerList(h.citationMarkers)}`, "");
    L.push(h.summary, "");
    L.push(`**Full statement.** ${h.content}`, "");
    L.push(`**Rationale.** ${h.rationale}`, "");
    if (h.keyAssumptions.length) {
      L.push(`**Key assumptions.**`, "");
      h.keyAssumptions.forEach((a) => L.push(`- ${a}`));
      L.push("");
    }
    if (h.verdict) {
      L.push(`*Review verdict: ${h.verdict}.*`, "");
    }
    if (h.protocol) {
      L.push(`**Proposed experiment.** ${h.protocol.overview}`, "");
      h.protocol.steps.forEach((s) =>
        L.push(`${s.step}. **${s.action}** — ${s.details}`),
      );
      L.push("", `*Timeline: ${h.protocol.timelineWeeks} weeks · Cost: ${h.protocol.costTier}.*`, "");
    }
  }

  L.push(`## 4. Discussion`, "", m.discussion, "");
  L.push(`## 5. Limitations`, "", m.limitations, "");

  L.push(`## References`, "");
  if (m.references.length === 0) {
    L.push(`*No citations were recorded for the ranked hypotheses.*`, "");
  } else {
    for (const e of m.references) {
      L.push(`${e.n}. ${formatReferenceText(e)}${CITATION_FLAG[e.status] ?? ""}`);
    }
    L.push("");
  }

  return L.join("\n");
}

// ─── LaTeX ───────────────────────────────────────────────────────────────────

/** Escape LaTeX special characters in body text. */
export function latexEscape(s: string): string {
  return s
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

function latexParagraphs(s: string): string {
  // Preserve blank-line paragraph breaks; escape each block.
  return s
    .split(/\n{2,}/)
    .map((p) => latexEscape(p.trim()))
    .filter(Boolean)
    .join("\n\n");
}

export function toLatex(m: Manuscript): string {
  const L: string[] = [];
  L.push(`\\documentclass[11pt]{article}`);
  L.push(`\\usepackage[utf8]{inputenc}`);
  L.push(`\\usepackage[margin=1in]{geometry}`);
  L.push(`\\usepackage{hyperref}`);
  L.push(`\\title{${latexEscape(m.title)}}`);
  L.push(`\\author{co-scientist}`);
  L.push(`\\date{${latexEscape(m.generatedAt)}}`);
  L.push(`\\begin{document}`);
  L.push(`\\maketitle`);

  L.push(`\\begin{abstract}`);
  L.push(latexParagraphs(m.abstract));
  L.push(`\\end{abstract}`);

  L.push(`\\section{Background}`);
  L.push(latexParagraphs(m.background));

  const me = m.methods;
  L.push(`\\section{Methods}`);
  L.push(
    latexEscape(
      `Hypotheses were generated and ranked by the co-scientist multi-agent pipeline ` +
        `(${me.agents.join(", ")}) using the ${me.model} language model` +
        `${me.seed != null ? `, seeded with ${me.seed} for reproducibility` : ""}. ` +
        `The run produced ${me.totalHypotheses} hypotheses over ${me.rounds} round(s), ` +
        `adjudicated through ${me.totalMatches} pairwise Glicko-2 tournament matches.`,
    ),
  );

  L.push(`\\section{Results}`);
  for (const h of m.hypotheses) {
    const markers = h.citationMarkers.length
      ? ` \\cite{${h.citationMarkers.map((n) => `ref${n}`).join(",")}}`
      : "";
    L.push(`\\subsection{${latexEscape(h.title)}}${markers}`);
    L.push(latexParagraphs(h.summary));
    L.push(`\\textbf{Full statement.} ${latexEscape(h.content)}`);
    L.push("");
    L.push(`\\textbf{Rationale.} ${latexEscape(h.rationale)}`);
  }

  L.push(`\\section{Discussion}`);
  L.push(latexParagraphs(m.discussion));
  L.push(`\\section{Limitations}`);
  L.push(latexParagraphs(m.limitations));

  if (m.references.length) {
    L.push(`\\begin{thebibliography}{${m.references.length}}`);
    for (const e of m.references) {
      L.push(`\\bibitem{ref${e.n}} ${latexEscape(formatReferenceText(e))}`);
    }
    L.push(`\\end{thebibliography}`);
  }

  L.push(`\\end{document}`);
  return L.join("\n");
}

// ─── Pandoc (DOCX / PDF) ──────────────────────────────────────────────────────

export interface PandocResult {
  ok: boolean;
  code: number;
  stderr: string;
}
export type PandocRunner = (args: string[], input: string) => PandocResult;

const defaultRunner: PandocRunner = (args, input) => {
  try {
    const proc = Bun.spawnSync({ cmd: ["pandoc", ...args], stdin: Buffer.from(input) });
    return {
      ok: proc.exitCode === 0,
      code: proc.exitCode ?? -1,
      stderr: proc.stderr ? new TextDecoder().decode(proc.stderr) : "",
    };
  } catch (e) {
    // ENOENT etc. — pandoc not installed.
    return { ok: false, code: 127, stderr: (e as Error).message };
  }
};

export function isPandocAvailable(runner: PandocRunner = defaultRunner): boolean {
  return runner(["--version"], "").ok;
}

/**
 * Convert the manuscript's Markdown to `toFormat` (e.g. "docx", "pdf") via pandoc,
 * writing to `outputPath`. Throws an actionable Error when pandoc is missing or fails.
 */
export function convertWithPandoc(
  markdown: string,
  toFormat: "docx" | "pdf",
  outputPath: string,
  runner: PandocRunner = defaultRunner,
): void {
  if (!isPandocAvailable(runner)) {
    throw new Error(
      `Pandoc is required to export ${toFormat.toUpperCase()} but was not found on PATH. ` +
        `Install it (https://pandoc.org/installing.html) or use --format md or --format latex instead.`,
    );
  }
  const res = runner(
    ["-f", "markdown", "-t", toFormat, "-o", outputPath],
    markdown,
  );
  if (!res.ok) {
    throw new Error(
      `Pandoc failed to produce ${toFormat.toUpperCase()} (exit ${res.code}): ${res.stderr.trim() || "unknown error"}` +
        (toFormat === "pdf" ? "\nPDF output additionally requires a LaTeX engine (e.g. TeX Live)." : ""),
    );
  }
}
